spring:
  kafka:
    properties:
      sasl.mechanism: PLAIN
      security.protocol: SASL_SSL
      basic.auth.credentials.source: USER_INFO
      auto.register.schemas: false
      use.latest.version: true
      specific.avro.reader: true
      value.deserializer.specific.avro.reader: true
      spring.json.trusted.packages: "*"
      bootstrap.servers: FIX
      sasl.jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule required username='FIX' password='FIX';
      basic.auth.user.info: FIX
      schema.registry.url: FIX
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer

      # JSON
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer

      # AVRO
      # value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      # value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer